export const BestDeals = [
  {
    id: 1,
    image: "/assets/aircooler.png",
    offer: ["15%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 2,
    image: "/assets/aircooler.png",
    offer: ["22%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 3,
    image: "/assets/aircooler.png",
    offer: ["18%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 4,
    image: "/assets/aircooler.png",
    offer: ["20%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 5,
    image: "/assets/aircooler.png",
    offer: ["25%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 6,
    image: "/assets/aircooler.png",
    offer: ["19%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 7,
    image: "/assets/aircooler.png",
    offer: ["21%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 8,
    image: "/assets/aircooler.png",
    offer: ["11%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 9,
    image: "/assets/aircooler.png",
    offer: ["21%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
  {
    id: 10,
    image: "/assets/aircooler.png",
    offer: ["11%", "OFF"],
    name: "Air Cooler",
    price: "8000",
  },
];
