export const flashdeals=[
    {
        id:1,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'50%'
    },
    {
        id:2,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'53%'
    },
    {
        id:3,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'45%'
    },
    {
        id:4,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'48%'
    },
    {
        id:5,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'54%'
    },
    {
        id:6,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'60%'
    },
    {
        id:7,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'43%'
    },
    {
        id:8,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'62%'
    },
    {
        id:9,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'70%'
    },
    {
        id:10,
        image:'/assets/buds.png',
        name:'Earbuds',
        price:'200',
        offer:'61%'
    },
]