export const swipperContent = [
  {
    id: 1,
    content1: "  Get unbeatable prices on the latest electronic devices by",
    content2: "",
    content3: "",
    content4: "",
    desc1: "  Shopping Online!",
    desc2: " ",
    desc3: "  ",
    desc4: " ",
    flex: "reverse",
    typing: "styles.letter",
    image: "/assets/products7.png",
    bgimage: "bg-[url(/assets/bg-6.webp)]",
  },
  {
    id: 2,
    content2: "Bo",
    content3: "a",
    content4: "t Rockers 370",
    desc1: "",
    desc2: "Upto 30% offer",
    desc3: "Don't miss it",
    desc4:
      "  Get lost in the music and find your perfect purchase with Boat headsets",
    flex: "reverse",
    typing: "",
    image: "/assets/headphone3.png",
    bgimage: "blue",
  },
  {
    id: 3,
    content1: "",
    content2: "",
    content3: "",
    content4: "TV",
    desc1: "",
    desc2: "Special Sale",
    desc3: "Upto 20% offer",
    desc4: "",
    desc5:
      "  Shop the latest TV models and enjoy the ultimate home viewing experience!",
    flex: "reverse",
    typing: "",
    image: "/assets/tv4 (1).png",
    bgimage: "bg-[url(/assets/bg-6.webp)]",
  },
];
